# Multiple Features

- Multiple variables $x_1, x_2, x_3, x_4...$
    - for example: size, length, weight, height, etc.

## Notations

$n$ = number of features

$i$ = index of the training data in the training set

$x^{(i)}$= input (features) of $i^{th}$ training example

$x^{(i)}_j$= value of feature $j$ in $i^{th}$ training example

## Multivariate Linear Regression

$h_\theta(x) = \theta_0 + \theta_1x+\theta_2x_2+\theta_3x_3+\theta_4x_4+...$

for convenience of notation $x_0 = 1$

$x = \begin{bmatrix}
x_0\\ 
x_1\\ 
x_2\\ 
x_3\\ 
...\\
x_n
\end{bmatrix}$

$\theta = \begin{bmatrix}
\theta_0\\ 
\theta_1\\ 
\theta_2\\ 
\theta_3\\ 
...\\
\theta_n
\end{bmatrix}$

$h_\theta(x) = \theta_0x_0 + \theta_1x+\theta_2x_2+\theta_3x_3+\theta_4x_4+...$

$=\theta^Tx$

$\theta$ Transpose time x = hypothesis

$\theta^T = \begin{bmatrix}
\theta_0& 
\theta_1& 
\theta_2& 
\theta_3&
...&
\theta_n
\end{bmatrix}$

$x = \begin{bmatrix}
x_0\\ 
x_1\\ 
x_2\\ 
x_3\\ 
...\\
x_n
\end{bmatrix}$

### Gradient Descent

Parameters: $\theta_0, \theta_1,....,\theta_n$ is denoted as just $\theta$

$J(\theta_0, \theta_1, ...,\theta_n)$  is denoted as just $J(\theta)$

**Cost Function**

$J(\theta) = \frac{1}{2m}\sum_{i=1}^m(h_\theta(x^{(i)})-y^{(i)})^2$

Repeat {

$\theta_j := \theta_j - \alpha \frac{\partial}{\partial\theta_j}J(\theta)$

}

Algorithm (n ≥ 1):

Repeat {

$\theta_j := \theta_j-\alpha\frac{1}{m}\sum_{i=1}^m(h_\theta(x^{(i)})-y^{(i)})x^{(i)}_j$

}

The end $x^{(i)}_j$ term is the power rule from the partial derivative when the cost function's partial derivative taken in respect to $\theta_j$

$\frac{\partial}{\partial\theta_j}h_\theta(x) = \theta_0x_0 + \theta_1x+\theta_2x_2+\theta_3x_3+\theta_4x_4+... = x_j$

In [2]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# get audi car price dataset
# https://www.kaggle.com/adityadesai13/used-car-dataset-ford-and-mercedes
dataset = pd.read_csv('data/audi.csv')

# print dataset
dataset.iloc[:5,:]

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

In [4]:
# get only A4's
dataset['model'] = dataset['model'].str.strip()
a4_dataset = dataset[dataset['model'] == "A4"]
a4_dataset.iloc[:5,:]

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
3     A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
7     A4  2016  11750       Manual    75185   Diesel   20  70.6         2.0
25    A4  2017  18500    Automatic    17418   Diesel  145  62.8         2.0
28    A4  2018  17200    Automatic    25138   Diesel  145  70.6         2.0
38    A4  2017  16000       Manual    29063   Diesel  145  70.6         2.0

In [28]:
# features are: mileage, tax, mpg, and engine size
# input data of x0, x1, x2, ...
# x0 is set to 1 for matrix multiplicaiton

input_data = np.array([np.ones(a4_dataset.shape[0]), a4_dataset.mileage, a4_dataset.engineSize])
input_data = input_data.transpose(1, 0);
output_data = np.array(a4_dataset.price)
print(input_data)
print(output_data)

[[1.0000e+00 2.5952e+04 2.0000e+00]
 [1.0000e+00 7.5185e+04 2.0000e+00]
 [1.0000e+00 1.7418e+04 2.0000e+00]
 ...
 [1.0000e+00 2.3700e+04 2.0000e+00]
 [1.0000e+00 7.8000e+04 3.0000e+00]
 [1.0000e+00 9.5000e+04 2.0000e+00]]
[16800 11750 18500 ... 20995  9995  6995]


In [42]:
# hypothesis funciton
def hypothesis_function(input_data, thetas):
    # transpose theta so it is now vertical and ready for multiplcation
    thetasT = thetas.reshape(1, thetas.shape[0])
    # multiply to find the prediction value
    return np.matmul(thetasT, input_data)

# cost function
def cost_function(inputs, outputs, thetas):
    sum_cost = 0
    m = inputs.shape[0]
    # sum of the difference squared / 2m
    for i in range(m):
        sum_cost += np.square(hypothesis_function(inputs[i], thetas) - outputs[i])
    return sum_cost / (2 * m)

def partial_derivative(inputs, outputs, thetas, x_terms):
    sum_d = 0
    m = inputs.shape[0]
    # sum of the difference * the matching feature x_term / m
    for i in range(m):
        sum_d += (hypothesis_function(inputs[i], thetas) - outputs[i]) * x_terms[i]
    return sum_d / m

def gradient_descent(inputs, outputs, thetas, alpha):
    new_thetas = np.zeros(thetas.shape[0])
    # for each theta calculate the partial derivative
    for j in range(thetas.shape[0]):
        # use inputs[:,j] to get the corresponding feature column
        step = alpha * partial_derivative(inputs, outputs, thetas, inputs[:,j])
        new_thetas[j] = thetas[j] - step
    return new_thetas

# learning rate
a = 1.5
iterations = 1000

# parameters
_thetas = np.zeros(input_data.shape[1])

normalized_input_data = np.zeros((input_data.shape[0], input_data.shape[1]))
for i in range(0, input_data.shape[1]):
    if (i == 0):
        for j in range(input_data.shape[0]):
            normalized_input_data[j,i] = 1
    else:
        a_max = np.max(input_data[:,i])
        a_min = np.min(input_data[:,i])
        for j in range(input_data.shape[0]):
            normalized_input_data[j, i] = input_data[j, i] / (a_max - a_min)
print(normalized_input_data)
print('cost before:', cost_function(normalized_input_data, output_data, _thetas))

for i in range(iterations):
    _thetas = gradient_descent(normalized_input_data, output_data, _thetas, a)
    print("iteration: ", i, "cost: ", cost_function(normalized_input_data, output_data, _thetas))
    
print('cost after:',cost_function(normalized_input_data, output_data, _thetas))

fig = plt.figure()
ax = plt.axes(projection="3d")

ax.scatter3D(normalized_input_data[:,1], normalized_input_data[:,2], output_data)

x_lin = np.linspace(0, np.max(normalized_input_data[:,1]), normalized_input_data.shape[0])
y_lin = np.linspace(0, np.max(normalized_input_data[:,2]), normalized_input_data.shape[0])
z_lin = np.zeros(normalized_input_data.shape[0])

for i in range(normalized_input_data.shape[0]):
    z_lin[i] = hypothesis_function([1, x_lin[i], y_lin[i]], _thetas)
    
def fun(x, y):
    return x**2 + y
    
X, Y = np.meshgrid(x_lin, y_lin)
zs = np.array(fun(np.ravel(X), np.ravel(Y)))
Z = zs.reshape(X.shape)
ax.plot_surface(X, Y, Z)

print(hypothesis_function([1, 10000, 2], _thetas))

ax.set_xlabel("Milage (miles)")
ax.set_ylabel("Engine Size")
ax.set_zlabel("Price ($)")

print(_thetas)

[[1.         0.1753632  0.47619048]
 [1.         0.50804108 0.47619048]
 [1.         0.11769714 0.47619048]
 ...
 [1.         0.16014596 0.47619048]
 [1.         0.52706264 0.71428571]
 [1.         0.64193527 0.47619048]]
cost before: [2.38624623e+08]
iteration:  0 cost:  [2.01136342e+08]
iteration:  1 cost:  [1.69972309e+08]
iteration:  2 cost:  [1.44051461e+08]
iteration:  3 cost:  [1.22478806e+08]
iteration:  4 cost:  [1.04513278e+08]
iteration:  5 cost:  [89541152.10816734]
iteration:  6 cost:  [77054070.16496317]
iteration:  7 cost:  [66630858.87655707]
iteration:  8 cost:  [57922498.73074442]
iteration:  9 cost:  [50639690.26148445]
iteration:  10 cost:  [44542570.00184596]
iteration:  11 cost:  [39432203.58296182]
iteration:  12 cost:  [35143548.29352237]
iteration:  13 cost:  [31539630.74027502]
iteration:  14 cost:  [28506729.32867099]
iteration:  15 cost:  [25950387.71829566]
iteration:  16 cost:  [23792115.52577628]
iteration:  17 cost:  [21966657.44423519]
iteration:  18 co

iteration:  194 cost:  [9655585.21821453]
iteration:  195 cost:  [9654546.98312108]
iteration:  196 cost:  [9653529.51877804]
iteration:  197 cost:  [9652532.40959478]
iteration:  198 cost:  [9651555.24830126]
iteration:  199 cost:  [9650597.63578064]
iteration:  200 cost:  [9649659.18090593]
iteration:  201 cost:  [9648739.50037943]
iteration:  202 cost:  [9647838.21857579]
iteration:  203 cost:  [9646954.96738803]
iteration:  204 cost:  [9646089.38607685]
iteration:  205 cost:  [9645241.12112273]
iteration:  206 cost:  [9644409.82608147]
iteration:  207 cost:  [9643595.16144206]
iteration:  208 cost:  [9642796.79448793]
iteration:  209 cost:  [9642014.39916078]
iteration:  210 cost:  [9641247.65592712]
iteration:  211 cost:  [9640496.25164753]
iteration:  212 cost:  [9639759.87944862]
iteration:  213 cost:  [9639038.23859758]
iteration:  214 cost:  [9638331.03437915]
iteration:  215 cost:  [9637637.97797503]
iteration:  216 cost:  [9636958.7863459]
iteration:  217 cost:  [9636293.182

KeyboardInterrupt: 