# Linear Algebra Review

## Matrix

Rectangular array of numbers

**2 by 3 matrix**

$\begin{bmatrix}
1 & 2 & 3\\
a & b & c
\end{bmatrix}$

Dimension of matrix: number of r**ows** x number of **columns**

### Matrix Element

Entries of matrix

$A_{ij} =$  "$i,j$ entry" in the $i^{th}$ row, $j^{th}$ column

## Vector

An n x 1 matrix

$\begin{bmatrix}
 1 \\
 2 \\
 3 \\
 4 
\end{bmatrix}$

In [2]:
import numpy as np

## Operations

### Addition

$\begin{aligned} {A}+{B} &= \left[\begin{array}{rr}{4} &{8} \\ {3} & {7} \end{array}\right]+\left[\begin{array}{rr}{{1}} &{0} \\{5} & {2} \end{array}\right]  &= \left[\begin{array}{rr}{4+{1}} &{8}+{0} \\{ 3}+{5} & 7+2 \end{array}\right]  &= \left[\begin{array}{rr}{5} &8 \\ 8 & 9 \end{array}\right] \end{aligned}$

In [4]:
A = np.array([[4, 8], [3, 7]])
B = np.array([[1, 0], [5, 2]])
print(A + B)

[[5 8]
 [8 9]]


### Scalar Multiplication

$\begin{aligned} \ 2\cdot\left[ \begin{array}{cc} 5 & 2 \\ 3 & 1 \end{array} \right] &=\left[ \begin{array}{cc} \ 2\cdot 5 & \ 2\cdot 2 \\ \ 2\cdot 3 & \ 2\cdot 1 \end{array} \right] &=\left[ \begin{array}{cc} 10 & 4 \\ 6 & 2 \end{array} \right] \end{aligned}$

In [21]:
A = np.array([[5, 2], [3, 1]])
print(2 * A)

[[10  4]
 [ 6  2]]


### Vector Matrix Multiplication

$\begin{bmatrix}1 & 3 \\4 & 0 \\2 & 1 \end{bmatrix}\begin{bmatrix}1\\ 5\end{bmatrix}=\begin{bmatrix}1 \times 1 + 3 \times 5\\ 4 \times 1 + 0 \times 5\\ 2 \times 1 + 1 \times 5\end{bmatrix}=\begin{bmatrix}16\\ 4\\ 7\end{bmatrix}$

In [18]:
A = np.array([[1, 3], [4, 0], [2, 1]])
B = np.array([1, 5])
print (np.matmul(A,B))

[16  4  7]


## Vector Matrix Application

$x = [234, 186, 162]$

$\theta_0 = 1$

$\theta_1 = 5$

$\begin{bmatrix}1 & 234 \\1 & 186 \\1 & 162 \end{bmatrix}\begin{bmatrix}1\\ 5\end{bmatrix}=\begin{bmatrix}1 \times 1 + 234 \times 5\\ 1 \times 1 + 186 \times 5\\ 1 \times 1 + 162 \times 5\end{bmatrix}$

Equivalent to

$h_\theta(x) = \theta_0 + \theta_1x$

Simplified code and computationally more efficient

## Matrix Matrix Multiplication
$\begin{bmatrix} 1 &3  &2 \\ 4 &0  &1 \end{bmatrix} \begin{bmatrix} 1 &3  \\ 0 &1  \\ 5 &2 \end{bmatrix} = \begin{bmatrix} 11 &10  \\ 9 &14 \end{bmatrix}$

$\begin{bmatrix} 1 &3  &2 \\ 4 &0  &1 \end{bmatrix} \begin{bmatrix} 1  \\ 0  \\ 5 \end{bmatrix} = \begin{bmatrix} 11  \\ 9 \end{bmatrix}$ 

$\begin{bmatrix} 1 &3  &2 \\ 4 &0  &1 \end{bmatrix} \begin{bmatrix} 3  \\ 1  \\ 2 \end{bmatrix} = \begin{bmatrix} 10  \\ 14 \end{bmatrix}$

m x n matrix (m rows n columns)

n x o matrix (n rows o columns)

result is a **m x o (m rows o columns) matrix**

In [16]:
A = np.array([[1, 3, 2], [4, 0, 1]])
B = np.array([[1, 3], [0, 1], [5, 2]])
print (np.matmul(A,B))

[[11 10]
 [ 9 14]]


## Properties

- Not Communicative $A \times B\not= B \times A$
- Associative $(A \times B) \times C = A \times (B \times C)$
- Identity Matrix $A \times I = I \times A = A$

    $\begin{bmatrix}
    1 & 0 & 0 & 0 \\ 
    0 & 1 & 0 & 0 \\0 & 0 & 1 & 0 \\ 
    0 & 0 & 0 & 1
    \end{bmatrix}$

In [22]:
A = np.array([[1, 3, 2], [4, 0, 1]])
B = np.array([[1, 3], [0, 1], [5, 2]])
print (np.matmul(A,B), " != ", np.matmul(B,A))

[[11 10]
 [ 9 14]]  !=  [[13  3  5]
 [ 4  0  1]
 [13 15 12]]


### Inverse

if A is an m x m matrix, and if it has an inverse,

$AA^{-1}=A^{-1}A = I$

In [26]:
from numpy.linalg import inv
a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)
print(np.matmul(a, ainv))
print(np.matmul(ainv, a))

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


### Transpose

$A = \begin{bmatrix}
1 &2  &0 \\ 
3 &5  &9 
\end{bmatrix}$

$A^T = \begin{bmatrix}
1 &3\\ 
2 &5\\ 
0 &9
\end{bmatrix}$

Let $A$ be an m x n matrix, and let $B = A^T$

Then $B$ is an n x m matrix, and $B_{ij} = A_{ji}$

In [34]:
A = np.array([[1, 2, 0], [3, 5, 9]])
# swaps axis-0 with axis-1
# swaps axis-1 with axis-0
Atranspose = A.transpose(1, 0)
print (Atranspose)

[[1 3]
 [2 5]
 [0 9]]
